version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: inoor
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank
      SPRING_DATASOURCE_USERNAME: inoor
      SPRING_DATASOURCE_PASSWORD: postgres_password
    depends_on:
      - db

